# Generated by Django 3.2.25 on 2025-06-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
